// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: devicesim.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_devicesim_2eproto__INCLUDED
#define GRPC_devicesim_2eproto__INCLUDED

#include "devicesim.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace devicesim {

// The greeting service definition.
class DeviceService final {
 public:
  static constexpr char const* service_full_name() {
    return "devicesim.DeviceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::devicesim::DeviceReply>> DeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::devicesim::DeviceReply>>(DeviceVariablesValuesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::devicesim::DeviceReply>> AsyncDeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::devicesim::DeviceReply>>(AsyncDeviceVariablesValuesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::devicesim::DeviceReply>> PrepareAsyncDeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::devicesim::DeviceReply>>(PrepareAsyncDeviceVariablesValuesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest* request, ::grpc::ClientReadReactor< ::devicesim::DeviceReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::devicesim::DeviceReply>* DeviceVariablesValuesRaw(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::devicesim::DeviceReply>* AsyncDeviceVariablesValuesRaw(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::devicesim::DeviceReply>* PrepareAsyncDeviceVariablesValuesRaw(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::devicesim::DeviceReply>> DeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::devicesim::DeviceReply>>(DeviceVariablesValuesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::devicesim::DeviceReply>> AsyncDeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::devicesim::DeviceReply>>(AsyncDeviceVariablesValuesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::devicesim::DeviceReply>> PrepareAsyncDeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::devicesim::DeviceReply>>(PrepareAsyncDeviceVariablesValuesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DeviceVariablesValues(::grpc::ClientContext* context, const ::devicesim::DeviceRequest* request, ::grpc::ClientReadReactor< ::devicesim::DeviceReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::devicesim::DeviceReply>* DeviceVariablesValuesRaw(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request) override;
    ::grpc::ClientAsyncReader< ::devicesim::DeviceReply>* AsyncDeviceVariablesValuesRaw(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::devicesim::DeviceReply>* PrepareAsyncDeviceVariablesValuesRaw(::grpc::ClientContext* context, const ::devicesim::DeviceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DeviceVariablesValues_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* context, const ::devicesim::DeviceRequest* request, ::grpc::ServerWriter< ::devicesim::DeviceReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_DeviceVariablesValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeviceVariablesValues() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DeviceVariablesValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/, ::grpc::ServerWriter< ::devicesim::DeviceReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeviceVariablesValues(::grpc::ServerContext* context, ::devicesim::DeviceRequest* request, ::grpc::ServerAsyncWriter< ::devicesim::DeviceReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DeviceVariablesValues<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DeviceVariablesValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeviceVariablesValues() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::devicesim::DeviceRequest, ::devicesim::DeviceReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::devicesim::DeviceRequest* request) { return this->DeviceVariablesValues(context, request); }));
    }
    ~WithCallbackMethod_DeviceVariablesValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/, ::grpc::ServerWriter< ::devicesim::DeviceReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::devicesim::DeviceReply>* DeviceVariablesValues(
      ::grpc::CallbackServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DeviceVariablesValues<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DeviceVariablesValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeviceVariablesValues() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DeviceVariablesValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/, ::grpc::ServerWriter< ::devicesim::DeviceReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeviceVariablesValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeviceVariablesValues() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DeviceVariablesValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/, ::grpc::ServerWriter< ::devicesim::DeviceReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeviceVariablesValues(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeviceVariablesValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeviceVariablesValues() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->DeviceVariablesValues(context, request); }));
    }
    ~WithRawCallbackMethod_DeviceVariablesValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/, ::grpc::ServerWriter< ::devicesim::DeviceReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* DeviceVariablesValues(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_DeviceVariablesValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_DeviceVariablesValues() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::devicesim::DeviceRequest, ::devicesim::DeviceReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::devicesim::DeviceRequest, ::devicesim::DeviceReply>* streamer) {
                       return this->StreamedDeviceVariablesValues(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_DeviceVariablesValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeviceVariablesValues(::grpc::ServerContext* /*context*/, const ::devicesim::DeviceRequest* /*request*/, ::grpc::ServerWriter< ::devicesim::DeviceReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedDeviceVariablesValues(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::devicesim::DeviceRequest,::devicesim::DeviceReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_DeviceVariablesValues<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_DeviceVariablesValues<Service > StreamedService;
};
// Sends a greeting
// rpc SayHello (DeviceRequest) returns (HelloReply) {}

}  // namespace devicesim


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_devicesim_2eproto__INCLUDED
